### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by ihussain1024** [abrantessouza/php2epl#2]
How is works when
$host = $this->host;
Means if it is not for shared printer, it directly connected to computer.

Any help will be appreciated.

**Comment by abrantessouza** [comment]
Hi,

This script works fine with Windows shared printer. I didn't make a
solution With local/directly device usb connected.

Best Regards!!

Em 14/02/2017 04:27, "ihussain" <notifications@github.com> escreveu:
